export const ADMIN_ROUTE = "/admin"
export const LOGIN_ROUTE = "/auth"
export const REGISTRATION_ROUTE = "/registration"
export const REQUEST_ROUTE = "/request"
export const MAKE_REQUEST_ROUTE = "/make_request"